/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_walnut_kanjian_app_ui_upload_GPUimageutil_GPUImageNativeLibrary */

#ifndef _Included_name_walnut_kanjian_app_ui_upload_GPUimageutil_GPUImageNativeLibrary
#define _Included_name_walnut_kanjian_app_ui_upload_GPUimageutil_GPUImageNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     name_walnut_kanjian_app_ui_upload_GPUimageutil_GPUImageNativeLibrary
 * Method:    YUVtoRBGA
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_name_walnut_kanjian_app_ui_upload_GPUimageutil_GPUImageNativeLibrary_YUVtoRBGA
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

/*
 * Class:     name_walnut_kanjian_app_ui_upload_GPUimageutil_GPUImageNativeLibrary
 * Method:    YUVtoARBG
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_name_walnut_kanjian_app_ui_upload_GPUimageutil_GPUImageNativeLibrary_YUVtoARBG
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
